### ISSUE TITLE
Donkere versie

### ISSUE THREAD

**Issue by haampie** [noslite/noslite#3]
Een donkere versie zou ook wel mooi zijn. Minimale CSS daarvoor:

```css
body {
    background: #111;
    color: #ccc;
}
a {
    color: #ccc;
}
```
